### ISSUE TITLE
Undefined method `ci' for  Datadog::Configuration error

### ISSUE THREAD

**Issue by jestinsebastian** [DataDog/datadog-ci-rb#255]
Hi,

We are trying to add test optimization for our rspec unit tests. I followed the steps mentioned [here](https://docs.datadoghq.com/tests/setup/ruby/?tab=cloudciprovideragentless). But while running the tests in CircleCI, we are getting the below error? 

```
An error occurred while loading spec_helper.
Failure/Error: c.ci.enabled = true

NoMethodError:
  undefined method `ci' for #<Datadog::Configuration::Settings:0x000055962b58b530>
# ./spec/spec_helper.rb:37:in `block in <top (required)>'
# ./spec/spec_helper.rb:35:in `<top (required)>'
```

Is this due to some configuration mismatch from our side? Please let me know if you want any more details.

Ruby Version :- 2.7.0
Rspec Version :- 3.10.0

This is the diff after adding the datadog-ci gem

```
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -243,13 +243,20 @@ GEM
       activerecord (>= 5.a)
       database_cleaner-core (~> 2.0.0)
     database_cleaner-core (2.0.1)
+    datadog (2.5.0)
+      datadog-ruby_core_source (~> 3.3)
+      libdatadog (~> 13.1.0.1.0)
+      libddwaf (~> 1.15.0.0.0)
+      msgpack
+    datadog-ci (1.8.1)
+      datadog (~> 2.4)
+      msgpack
+    datadog-ruby_core_source (3.3.6)
     date (3.4.0)
-    ddtrace (1.8.0)
-      debase-ruby_core_source (>= 0.10.16, <= 0.10.18)
-      libdatadog (~> 0.9.0.1.0)
-      libddwaf (~> 1.5.1.0.0)
+    ddtrace (0.54.2)
+      debase-ruby_core_source (<= 0.10.14)
       msgpack
-    debase-ruby_core_source (0.10.18)
+    debase-ruby_core_source (0.10.14)
```

**Comment by anmarchenko** [comment]
Hi! Thanks for contacting us.

I think the problem is that you have conflicting Datadog ruby gems (datadog 2.5 and ddtrace 0.54):
- ddtrace gem was renamed to datadog as of version 2.0
- datadog-ci gem requires gem datadog v2.5 to be present, it is incompatible with ddtrace

If you don't use Datadog APM, you can safely remove ddtrace from your Gemfile.
If you use Datadog APM please follow the guides to upgrade to datadog v2:
- 0.x to 1.x: https://github.com/DataDog/dd-trace-rb/blob/master/docs/UpgradeGuide.md
- 1.x to datadog 2.x: https://github.com/DataDog/dd-trace-rb/blob/master/docs/UpgradeGuide2.md

**Comment by jestinsebastian** [comment]
That was it. Thank you
